services:
    backup-agent:
        image: backup-agent:latest
        container_name: backup-agent
        ports:
            - "3000:3000"
        volumes:
            - backup_data:/data
        env_file:
            - .env
        restart: unless-stopped

volumes:
    backup_data:
