version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: sh -c 'minio server /data --console-address ":9001" &'
    entrypoint: |
      /bin/bash -c "
      minio server /data --console-address \":9001\" &
      /opt/bin/wait-for-it.sh localhost:9000 --timeout 60 --strict -- /bin/bash -c '
      /opt/bin/mc alias set myminio http://localhost:9000 minio minio123;
      /opt/bin/mc admin user add myminio myuser mypassword;
      '
      wait %1
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"] # Removed quotes around the whole command
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data: